services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - ~/.m2:/root/.m2:delegated
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MAVEN_OPTS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_VERSION:-10.6}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    env_file:
      - ./server/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-integrated_cms}
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-admin123}
    ports:
      - "${DB_PORT:-3306}:3306"
    command: 
      - --character-set-server=${MARIADB_CHARSET:-utf8mb4}
      - --collation-server=${MARIADB_COLLATION:-utf8mb4_unicode_ci}
      - --skip-character-set-client-handshake

volumes:
  mysql_data: