-- 통합 CMS v2 데이터베이스 스키마

-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS integrated_cms DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 계정 생성 및 권한 설정
-- integrated.admin: 통합 CMS DB와 모든 서비스 DB 접근 권한
CREATE USER 'integrated.admin'@'%' IDENTIFIED BY 'your_secure_password';
GRANT ALL PRIVILEGES ON integrated_cms.* TO 'integrated.admin'@'%';
GRANT ALL PRIVILEGES ON douzone.* TO 'integrated.admin'@'%';
-- 추가 서비스 DB가 생성될 때마다 GRANT 명령어 추가

-- admin: 서비스 DB만 접근 권한
CREATE USER 'admin'@'%' IDENTIFIED BY 'your_secure_password';
GRANT ALL PRIVILEGES ON douzone.* TO 'admin'@'%';
-- 추가 서비스 DB가 생성될 때마다 GRANT 명령어 추가

FLUSH PRIVILEGES;

-- 통합 CMS DB 사용
USE integrated_cms;

-- 0. 관리자 사용자 테이블 (기존 user 테이블 구조 기반)
CREATE TABLE ADMIN_USER (
    UUID VARCHAR(36) NOT NULL COMMENT '관리자 고유 ID',
    USERNAME VARCHAR(50) NOT NULL COMMENT '관리자 계정명',
    NAME VARCHAR(100) NOT NULL COMMENT '관리자 이름',
    EMAIL VARCHAR(100) NOT NULL COMMENT '이메일',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '암호화된 비밀번호',
    ROLE VARCHAR(20) NOT NULL COMMENT '관리자 역할',
    AVATAR_URL VARCHAR(255) DEFAULT NULL COMMENT '프로필 이미지 URL',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '계정 상태',
    ORGANIZATION_ID VARCHAR(36) DEFAULT NULL COMMENT '기관 ID',
    GROUP_ID VARCHAR(36) DEFAULT NULL COMMENT '그룹 ID',
    PHONE VARCHAR(50) DEFAULT NULL COMMENT '전화번호',
    TEMP_PW_FLAG TINYINT(1) DEFAULT 0 COMMENT '임시비밀번호여부 (0: 아니오, 1: 예)',
    PROVIDER VARCHAR(50) DEFAULT NULL COMMENT '인증 제공자',
    RESET_TOKEN VARCHAR(255) DEFAULT NULL COMMENT '비밀번호 재설정 토큰',
    RESET_TOKEN_EXPIRY TIMESTAMP NULL DEFAULT NULL COMMENT '비밀번호 재설정 토큰 만료 시간',
    IS_TEMPORARY TINYINT(1) DEFAULT 0 COMMENT '임시 관리자 여부 (0: 아니오, 1: 예)',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    MEMO TEXT DEFAULT NULL COMMENT '관리자 메모 내용',
    MEMO_UPDATED_AT TIMESTAMP NULL DEFAULT NULL COMMENT '메모 최종 수정 일시',
    MEMO_UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '메모 최종 수정자 UUID',
    PRIMARY KEY (UUID),
    UNIQUE KEY username (USERNAME),
    UNIQUE KEY email (EMAIL),
    KEY created_by (CREATED_BY),
    KEY updated_by (UPDATED_BY),
    KEY fk_admin_memo_updated_by (MEMO_UPDATED_BY),
    CONSTRAINT fk_admin_memo_updated_by FOREIGN KEY (MEMO_UPDATED_BY) REFERENCES ADMIN_USER (UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT admin_user_ibfk_1 FOREIGN KEY (CREATED_BY) REFERENCES ADMIN_USER (UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT admin_user_ibfk_2 FOREIGN KEY (UPDATED_BY) REFERENCES ADMIN_USER (UUID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '통합 관리자 계정 관리';

-- 1. 서비스 관리
CREATE TABLE SERVICE (
    SERVICE_ID VARCHAR(36) NOT NULL COMMENT '서비스 고유 ID',
    SERVICE_CODE VARCHAR(50) NOT NULL COMMENT '서비스 코드 (중복 불가)',
    SERVICE_NAME VARCHAR(100) NOT NULL COMMENT '서비스 이름',
    SERVICE_DOMAIN VARCHAR(255) COMMENT '서비스 도메인 (예: https://example.com)',
    API_BASE_URL VARCHAR(255) COMMENT 'API 기본 URL',
    DB_CONNECTION_INFO TEXT COMMENT '암호화된 DB 접속 정보',
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '서비스 상태 (ACTIVE, INACTIVE, MAINTENANCE)',
    DESCRIPTION TEXT COMMENT '서비스 설명',
    CONFIG JSON COMMENT '서비스 설정 정보',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    PRIMARY KEY (SERVICE_ID),
    UNIQUE KEY unique_service_code (SERVICE_CODE),
    FOREIGN KEY (CREATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (UPDATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    KEY idx_service_code (SERVICE_CODE),
    KEY idx_status_created (STATUS, CREATED_AT),
    KEY idx_domain (SERVICE_DOMAIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '서비스 정보 관리';

-- 2. 서비스별 권한 그룹 관리
CREATE TABLE SERVICE_GROUP (
    GROUP_ID VARCHAR(36) NOT NULL COMMENT '그룹 고유 ID',
    SERVICE_ID VARCHAR(36) NOT NULL COMMENT '서비스 ID',
    GROUP_CODE VARCHAR(50) NOT NULL COMMENT '그룹 코드',
    GROUP_NAME VARCHAR(100) NOT NULL COMMENT '그룹명',
    DESCRIPTION TEXT COMMENT '그룹 설명',
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '그룹 상태',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    PRIMARY KEY (GROUP_ID),
    UNIQUE KEY unique_service_group_code (SERVICE_ID, GROUP_CODE),
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (UPDATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    KEY idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '서비스별 권한 그룹 관리';

-- 3. 서비스별 회원-그룹 매핑
CREATE TABLE SERVICE_MEMBER_GROUP (
    SERVICE_ID VARCHAR(36) NOT NULL COMMENT '서비스 ID',
    USER_UUID VARCHAR(36) NOT NULL COMMENT '회원 UUID',
    GROUP_ID VARCHAR(36) NOT NULL COMMENT '그룹 ID',
    IS_ADMIN TINYINT(1) DEFAULT 0 COMMENT '서비스 관리자 여부 (0: 아니오, 1: 예)',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    PRIMARY KEY (SERVICE_ID, USER_UUID),
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES SERVICE_GROUP(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (USER_UUID) REFERENCES `user`(uuid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (UPDATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    KEY idx_group_id (GROUP_ID),
    KEY idx_user_uuid (USER_UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '서비스별 회원-그룹 매핑';

-- 4. 통합 권한 관리
CREATE TABLE SERVICE_PERMISSION (
    PERMISSION_ID VARCHAR(36) NOT NULL COMMENT '권한 매핑 고유 ID',
    SERVICE_ID VARCHAR(36) NOT NULL COMMENT '서비스 ID',
    GROUP_ID VARCHAR(36) DEFAULT NULL COMMENT '그룹 ID (개별 권한인 경우 NULL)',
    USER_UUID VARCHAR(36) DEFAULT NULL COMMENT '회원 UUID (그룹 권한인 경우 NULL)',
    PERMISSION_TYPE VARCHAR(20) NOT NULL COMMENT '권한 유형 (MENU, BOARD, CONTENT)',
    TARGET_ID VARCHAR(36) NOT NULL COMMENT '대상 ID',
    TARGET_NAME VARCHAR(100) NOT NULL COMMENT '대상 이름',
    PERMISSION_LEVEL VARCHAR(20) NOT NULL DEFAULT 'READ' COMMENT '권한 레벨 (READ, WRITE, ADMIN)',
    IS_ADDITIONAL TINYINT(1) DEFAULT 0 COMMENT '추가 권한 여부 (0: 기본권한, 1: 추가권한)',
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '권한 상태',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_IP VARCHAR(45) DEFAULT NULL COMMENT '생성 IP',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    UPDATED_BY VARCHAR(36) DEFAULT NULL COMMENT '수정자 ID',
    UPDATED_IP VARCHAR(45) DEFAULT NULL COMMENT '수정 IP',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
    PRIMARY KEY (PERMISSION_ID),
    UNIQUE KEY unique_permission (SERVICE_ID, GROUP_ID, USER_UUID, PERMISSION_TYPE, TARGET_ID, IS_ADDITIONAL),
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES SERVICE_GROUP(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (USER_UUID) REFERENCES `user`(uuid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (UPDATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    KEY idx_group_id (GROUP_ID),
    KEY idx_user_uuid (USER_UUID),
    KEY idx_permission_type (PERMISSION_TYPE, TARGET_ID),
    KEY idx_additional_status (IS_ADDITIONAL, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '통합 권한 관리';

-- 5. 권한 감사 로그
CREATE TABLE SERVICE_PERMISSION_LOG (
    LOG_ID VARCHAR(36) NOT NULL COMMENT '로그 고유 ID',
    SERVICE_ID VARCHAR(36) NOT NULL COMMENT '서비스 ID',
    PERMISSION_ID VARCHAR(36) NOT NULL COMMENT '권한 ID',
    USER_UUID VARCHAR(36) NOT NULL COMMENT '회원 UUID',
    ACTION VARCHAR(50) NOT NULL COMMENT '수행 작업',
    BEFORE_LEVEL VARCHAR(20) DEFAULT NULL COMMENT '변경 전 권한 레벨',
    AFTER_LEVEL VARCHAR(20) DEFAULT NULL COMMENT '변경 후 권한 레벨',
    IS_ADDITIONAL TINYINT(1) DEFAULT NULL COMMENT '추가 권한 여부',
    STATUS VARCHAR(20) NOT NULL COMMENT '처리 상태',
    REQUEST_IP VARCHAR(45) DEFAULT NULL COMMENT '요청 IP',
    CREATED_BY VARCHAR(36) DEFAULT NULL COMMENT '생성자 ID',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
    PRIMARY KEY (LOG_ID),
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES SERVICE_PERMISSION(PERMISSION_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (USER_UUID) REFERENCES `user`(uuid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES ADMIN_USER(UUID) ON DELETE SET NULL ON UPDATE CASCADE,
    KEY idx_service_time (SERVICE_ID, CREATED_AT),
    KEY idx_user_time (USER_UUID, CREATED_AT),
    KEY idx_permission (PERMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '권한 변경 이력';

-- ========================================
-- 샘플 데이터 및 동적 DB 연결 설정 예시
-- ========================================

-- 샘플 서비스 데이터 (douzone 서비스 예시)
INSERT INTO SERVICE (
    SERVICE_ID, 
    SERVICE_CODE, 
    SERVICE_NAME, 
    SERVICE_DOMAIN, 
    API_BASE_URL,
    DB_CONNECTION_INFO,
    STATUS,
    DESCRIPTION,
    CONFIG,
    CREATED_BY,
    CREATED_AT
) VALUES (
    'service-001',
    'douzone',
    'Douzone CMS 서비스',
    'https://douzone.example.com',
    'https://api.douzone.example.com',
    '{"driver":"org.mariadb.jdbc.Driver","url":"jdbc:mariadb://localhost:3306/douzone","username":"admin","password":"encrypted_password","maxPoolSize":20,"minIdle":5}',
    'ACTIVE',
    'Douzone 그룹 CMS 서비스',
    '{"theme":"default","timezone":"Asia/Seoul","locale":"ko_KR"}',
    'system',
    NOW()
);

-- 샘플 서비스 데이터 (service1 예시)
INSERT INTO SERVICE (
    SERVICE_ID, 
    SERVICE_CODE, 
    SERVICE_NAME, 
    SERVICE_DOMAIN, 
    API_BASE_URL,
    DB_CONNECTION_INFO,
    STATUS,
    DESCRIPTION,
    CONFIG,
    CREATED_BY,
    CREATED_AT
) VALUES (
    'service-002',
    'service1',
    'Service1 CMS',
    'https://service1.example.com',
    'https://api.service1.example.com',
    '{"driver":"org.mariadb.jdbc.Driver","url":"jdbc:mariadb://localhost:3306/service1_db","username":"admin","password":"encrypted_password","maxPoolSize":15,"minIdle":3}',
    'ACTIVE',
    'Service1 전용 CMS 서비스',
    '{"theme":"modern","timezone":"Asia/Seoul","locale":"ko_KR"}',
    'system',
    NOW()
);

-- DB_CONNECTION_INFO 컬럼 설명:
-- 동적 DataSource 생성을 위한 암호화된 JSON 형태의 DB 연결 정보
-- 포함 정보: 드라이버, URL, 사용자명, 암호화된 비밀번호, 연결 풀 설정 등