FROM openjdk:17-slim

WORKDIR /app

# Install Maven
RUN apt-get update && \
    apt-get install -y maven

# Create directory for Maven local repository
RUN mkdir -p /root/.m2

# Copy source code will be mounted via volume

EXPOSE 8080

# Change working directory to where pom.xml is located
WORKDIR /app

CMD ["sh", "-c", "mvn clean spring-boot:run -Dspring-boot.run.profiles=dev -f /app/pom.xml"]